`timescale 1ns/1ps
`include "2_input_and.v"

module and_gate_tb;

  reg a, b;
  wire y;
  
  // Reference (expected output)
  wire y_ref;
  
  // Mismatch signal
  wire mismatch;
  
  // Instantiate DUT (Device Under Test)
  and_gate uut 
    (
        .a(a),
        .b(b),
        .y(y)
    );
    
    // Hardcoded reference logic (same AND behavior)
  assign y_ref = a & b;
  
  // Mismatch = 1 if output is wrong
  assign mismatch = (y !== y_ref);
  
  initial begin
      $dumpfile("and_gate.vcd");  // waveform file
      $dumpvars(0, and_gate_tb);
  
      // Test all cases
      a = 0; b = 0; #10;
      a = 0; b = 1; #10;
      a = 1; b = 0; #10;
      a = 1; b = 1; #10;
  
      $finish;
  end

endmodule